apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ofwrnabgn-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ofwrnabgn-java-springboot-gitops